export const ROUTES = {
  HOME: "/",
  PROPERTIES: "/properties",
  PROPERTY_DETAIL: (id: string) => `/properties/${id}`,
  DEVELOPERS: "/developers",
  DEVELOPER_DETAIL: (id: string) => `/developers/${id}`,
  SEARCH: "/search",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  UNAUTHORIZED: "/unauthorized",
  FORBIDDEN: "/forbidden",
  DASHBOARD: "/dashboard",
  LISTINGS: "/listings",
  NEW_LISTING: "/listings/new",
  EDIT_LISTING: (id: string) => `/listings/${id}/edit`,
  ANALYTICS: "/analytics",
  NOTIFICATIONS: "/notifications",
  PROFILE: "/profile",
  ADMIN: "/admin",
  ADMIN_DEVELOPERS: "/admin/developers",
  ADMIN_LISTINGS: "/admin/listings",
  ADMIN_REPORTS: "/admin/reports",
} as const;
